"use client";
import { useState } from "react";
import { ArrowRight, BarChart3, ChevronDown, Globe2, Leaf, Menu, MoveUpRight, ShieldCheck, Sprout, X } from "lucide-react";

const nav=["Story","Model","Market","Portfolio","ESG","Roadmap","FAQ"];
const metrics=[
  ["2017","Farm founded","Old Guia, Ma-ayon, Capiz"],
  ["2020","Founder transition","From seafaring to full-time farm + chocolate"],
  ["100%","Farm-connected","Cacao, post-harvest and chocolate under one story"],
  ["PH","Origin market","Built around Philippine cacao and local value creation"]
];
const products=[
  ["55% Milk Chocolate","Smooth, creamy cacao expression for a broad everyday audience."],
  ["70% Dark Chocolate","A deeper cacao-forward profile with restrained sweetness."],
  ["Artisanal Tablea","Traditional Filipino cacao drinking culture in a modern premium format."],
  ["Keto Chocolate","A reduced-sugar option for customers seeking another way to enjoy dark chocolate."]
];
const faqs=[
  ["What is O Guia Chocolates?","O Guia Chocolates is the chocolate expression of DADs Farm, connecting cacao farming, post-harvest work, chocolate making and Philippine origin into one brand story."],
  ["Where is DADs Farm?","The farm is in Brgy. Old Guia, Ma-ayon, Capiz, Philippines."],
  ["What are the figures on this page?","Investor metrics shown as placeholders are intentionally illustrative. Replace them with verified operating, financial, market and ESG data before publishing an investor deck or making investment decisions."],
  ["How can partners connect?","Use the contact section for wholesale, distribution, hospitality, investment and partnership inquiries."]
];

export default function Home(){
 const [open,setOpen]=useState(false); const [faq,setFaq]=useState<number|null>(null);
 const schema={"@context":"https://schema.org", "@graph":[
   {"@type":"Organization",name:"O Guia Chocolates by DADs Farm",url:"https://oguiachocolates.com",description:"Philippine cacao, bean-to-bar chocolate and farm-to-table enterprise rooted in Capiz."},
   {"@type":"WebSite",name:"O Guia Chocolates",url:"https://oguiachocolates.com"},
   {"@type":"LocalBusiness",name:"DADs Farm",address:{"@type":"PostalAddress",addressLocality:"Ma-ayon",addressRegion:"Capiz",addressCountry:"PH"}}
 ]};
 return <>
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} />
 <header className="fixed top-0 z-50 w-full border-b border-[#dfd4bd] bg-[#fdfbf7]/95 backdrop-blur-md">
  <div className="container flex h-[72px] items-center justify-between">
   <a href="#top" className="focus flex items-center gap-3" aria-label="O Guia Chocolates by DADs Farm"><img src="/oguia-logo.webp" alt="O Guia Chocolates by DADs Farm" className="h-12 w-12 object-contain" /><span><strong className="display text-lg">O Guia</strong><small className="block text-[9px] font-bold uppercase tracking-[.18em] text-[#8e6d31]">Chocolates by DADs Farm</small></span></a>
   <nav className="hidden items-center gap-7 lg:flex">{nav.map(n=><a key={n} href={'#'+n.toLowerCase()} className="focus text-[11px] font-bold uppercase tracking-[.12em] text-[#4a271d] hover:text-[#8e6d31]">{n}</a>)}<a className="btn btn-gold h-10 min-h-10" href="#contact">Investor / Partner <MoveUpRight size={14}/></a></nav>
   <button className="focus rounded-md p-2 lg:hidden" aria-label="Open menu" onClick={()=>setOpen(true)}><Menu/></button>
  </div>
  {open&&<div className="fixed inset-0 bg-[#241611] text-[#fdfbf7] lg:hidden"><div className="container pt-5"><div className="flex justify-between"><span className="display text-2xl">O Guia</span><button className="focus p-2" aria-label="Close menu" onClick={()=>setOpen(false)}><X/></button></div><div className="mt-14 grid gap-6">{nav.map(n=><a key={n} href={'#'+n.toLowerCase()} onClick={()=>setOpen(false)} className="display text-3xl">{n}</a>)}<a href="#contact" onClick={()=>setOpen(false)} className="btn btn-gold mt-4">Investor / Partner <ArrowRight size={16}/></a></div></div></div>}
 </header>

 <main id="top">
  <section className="relative flex min-h-[760px] items-end overflow-hidden bg-[#241611] pt-[72px] text-[#fdfbf7]">
   <img src="/images/cacao-farm.png" alt="Cacao agroforestry landscape at DADs Farm" className="absolute inset-0 h-full w-full object-cover opacity-70"/>
   <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(36,22,17,.98),rgba(36,22,17,.78)_48%,rgba(36,22,17,.25))]"/>
   <div className="container relative z-10 grid gap-12 pb-20 lg:grid-cols-[1.25fr_.75fr] lg:items-end">
    <div><div className="eyebrow text-[#c5a059]">Investor landing • Philippine cacao • Capiz</div><h1 className="display hero-title mt-5 max-w-4xl text-[72px] leading-[.96]">From our farm in Capiz to the world.</h1><p className="mt-7 max-w-2xl text-[16px] leading-8 text-[#f7f3eb]/85">A diversified farm-to-table enterprise connecting healthy soil, Philippine cacao, careful post-harvest work and O Guia Chocolates into a scalable origin story.</p><div className="mt-8 flex flex-wrap gap-3"><a className="btn btn-gold" href="#portfolio">Explore the opportunity <ArrowRight size={16}/></a><a className="btn btn-outline" href="#story">Our story</a></div></div>
    <div className="glass rounded-[22px] p-6"><div className="flex items-center justify-between"><span className="eyebrow text-[#c5a059]">Vision</span><Globe2 size={18} className="text-[#c5a059]"/></div><p className="display mt-5 text-2xl leading-snug">An ecologically sustainable diversified farm that champions healthy, naturally grown and affordable farm-to-table produce—while elevating O Guia Chocolates and artisanal tablea into world-renowned symbols of Philippine cacao.</p><div className="mt-6 h-px bg-[#c5a059]/40"/><div className="mt-5 grid grid-cols-3 gap-3 text-[10px] font-bold uppercase tracking-[.1em] text-[#f7f3eb]/70"><span>Restore</span><span>Empower</span><span>Transform</span></div></div>
   </div>
  </section>

  <section className="border-b border-[#dfd4bd] bg-[#f7f3eb]"><div className="container grid grid-cols-2 divide-x divide-[#dfd4bd] md:grid-cols-4">{metrics.map(([a,b,c])=><div key={a} className="px-5 py-8 first:pl-0 last:pr-0"><div className="display metric text-3xl text-[#241611]">{a}</div><div className="mt-1 text-xs font-extrabold uppercase tracking-[.12em] text-[#8e6d31]">{b}</div><p className="mt-2 text-xs leading-5 text-[#4a271d]/65">{c}</p></div>)}</div></section>

  <section id="story" className="section grid-paper"><div className="container grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><div className="eyebrow">01 / The story</div><h2 className="display mt-4 text-5xl leading-[1.02] md:text-6xl">Great chocolate begins beneath the soil.</h2><p className="mt-6 text-[15px] leading-8 text-[#4a271d]/75">DADs Farm began in 2017 on an idle property in Brgy. Old Guia, Ma-ayon, Capiz. What started as a farm dream evolved into a diversified landscape of cacao, fruit-bearing and native trees—and later, a chocolate venture built around Philippine origin.</p><p className="mt-4 text-[15px] leading-8 text-[#4a271d]/75">In 2020, founder Jose Roy Depon stepped away from seafaring to focus on the farm and chocolate full-time. Today the model is designed to keep more value connected to the source: farm, post-harvest, product and brand.</p><a className="mt-7 inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-[#8e6d31]" href="#model">See the model <ArrowRight size={15}/></a></div><div className="relative overflow-hidden rounded-[28px] bg-[#20362d] p-4 shadow-card"><div className="relative aspect-[4/3] overflow-hidden rounded-[20px]"><img src="/images/cacao-farm.png" alt="DADs Farm cacao agroforestry landscape" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#241611]/65 to-transparent"/><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between text-white"><span className="text-xs font-bold uppercase tracking-[.15em]">Old Guia · Ma-ayon · Capiz</span><Leaf size={22} className="text-[#c5a059]"/></div></div></div></div></section>

  <section id="model" className="section bg-[#241611] text-[#fdfbf7]"><div className="container"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><div className="eyebrow text-[#c5a059]">02 / Business model</div><h2 className="display mt-4 text-5xl leading-[1.02] md:text-6xl">One origin. Multiple value layers.</h2><p className="mt-6 max-w-md leading-7 text-[#f7f3eb]/70">The investor design treats the farm as the foundation and chocolate as a high-value consumer expression—supported by products, experiences, sourcing and future partnerships.</p></div><div className="grid gap-px overflow-hidden rounded-[18px] bg-[#c5a059]/25 md:grid-cols-2">{[["Farm","Cacao + diversified crops + biodiversity","01"],["Post-harvest","Fermentation + drying + quality systems","02"],["Chocolate","Bean-to-bar + tablea + product innovation","03"],["Market","Retail + wholesale + hospitality + tourism","04"]].map(([t,d,n])=><div key={n} className="bg-[#2b1b16] p-7"><div className="flex justify-between text-[#c5a059]"><Sprout size={21}/><span className="text-xs font-bold">{n}</span></div><h3 className="display mt-8 text-3xl">{t}</h3><p className="mt-2 text-sm leading-6 text-[#f7f3eb]/60">{d}</p></div>)}</div></div></div></section>

  <section id="market" className="section"><div className="container"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="eyebrow">03 / Market</div><h2 className="display mt-3 text-5xl md:text-6xl">The market map.</h2></div><p className="max-w-lg text-sm leading-7 text-[#4a271d]/70">Placeholder investor figures below are visual scaffolding only. Replace them with sourced market research and current operating data.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[["TAM","₱ XX.XB","Philippine + regional premium chocolate opportunity"],["SAM","₱ X.XB","Premium Filipino cacao / bean-to-bar segment"],["SOM","₱ XXXM","Illustrative near-term addressable share"]].map(([a,b,c])=><div key={a} className="shadow-card rounded-[18px] border border-[#dfd4bd] bg-[#f7f3eb] p-7"><div className="flex items-center justify-between"><span className="eyebrow">{a}</span><BarChart3 size={18} className="text-[#c5a059]"/></div><div className="display metric mt-7 text-5xl">{b}</div><p className="mt-3 text-sm leading-6 text-[#4a271d]/65">{c}</p></div>)}</div></div></section>

  <section id="portfolio" className="section bg-[#f7f3eb]"><div className="container"><div className="eyebrow">04 / Portfolio</div><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><h2 className="display mt-3 max-w-2xl text-5xl leading-[1.02] md:text-6xl">Products that carry the place.</h2><span className="pill w-fit text-[#8e6d31]">Placeholder portfolio figures</span></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.map(([t,d],i)=><article key={t} className="group overflow-hidden rounded-[18px] border border-[#dfd4bd] bg-[#fdfbf7]"><div className="relative h-52 overflow-hidden bg-[#241611]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_35%_30%,#a76b3f,#4a271d_52%,#241611)]"/><div className="absolute inset-5 grid place-items-center rounded-[12px] border border-[#c5a059]/45"><span className="display text-2xl text-[#fdfbf7]">O Guia</span></div><span className="absolute right-4 top-4 text-[10px] font-black uppercase tracking-[.16em] text-[#c5a059]">0{i+1}</span></div><div className="p-6"><h3 className="display text-2xl">{t}</h3><p className="mt-3 text-sm leading-6 text-[#4a271d]/65">{d}</p><a href="#contact" className="mt-5 inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-[#8e6d31]">Discuss product <ArrowRight size={13}/></a></div></article>)}</div></div></section>

  <section id="esg" className="section"><div className="container grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><div className="eyebrow">05 / ESG</div><h2 className="display mt-3 text-5xl leading-[1.02] md:text-6xl">Restore. Empower. Transform.</h2><p className="mt-6 leading-7 text-[#4a271d]/70">A working framework for linking commercial growth with farm resilience, livelihoods, local knowledge and responsible governance.</p></div><div className="grid gap-4">{[["Restore","Agroforestry, reforestation, biodiversity, soil health, water and resource stewardship.",Leaf],["Empower","Local sourcing, training, cacao knowledge, livelihoods and Philippine heritage.",ShieldCheck],["Transform","Value-added products, market access, better post-harvest systems and transparent growth.",Globe2]].map(([t,d,I])=>{const Icon=I as typeof Leaf; return <div key={t as string} className="rounded-[18px] border border-[#dfd4bd] p-6"><div className="flex items-start gap-5"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#2d4a3e] text-[#c5a059]"><Icon size={19}/></div><div><h3 className="display text-2xl">{t as string}</h3><p className="mt-2 text-sm leading-6 text-[#4a271d]/65">{d as string}</p></div></div></div>})}</div></div></section>

  <section id="roadmap" className="section bg-[#20362d] text-[#fdfbf7]"><div className="container"><div className="eyebrow text-[#c5a059]">06 / Roadmap & dashboard</div><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><h2 className="display mt-3 text-5xl leading-[1.02] md:text-6xl">Build the next layer.</h2><p className="mt-6 leading-7 text-[#f7f3eb]/65">A presentation-ready structure for milestones, operating targets and future capital deployment. Replace placeholder values with verified data.</p></div><div className="grid gap-4 sm:grid-cols-2">{[["Factory","XX%","Completion"],["Production","X,XXX kg","Annual target"],["Distribution","XX","Partner doors"],["Revenue","₱XX.XM","Illustrative target"]].map(([t,v,s])=><div key={t} className="rounded-[16px] border border-[#c5a059]/30 bg-[#20362d]/70 p-6"><div className="text-xs font-bold uppercase tracking-[.14em] text-[#c5a059]">{t}</div><div className="display metric mt-5 text-4xl">{v}</div><div className="mt-1 text-xs text-[#f7f3eb]/45">{s}</div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-[#fdfbf7]/10"><div className="h-full w-2/3 bg-[#c5a059]"/></div></div>)}</div></div></div></section>

  <section className="section"><div className="container"><div className="grid gap-12 lg:grid-cols-2"><div><div className="eyebrow">07 / Investment architecture</div><h2 className="display mt-3 text-5xl leading-[1.02]">Designed for diligence.</h2><p className="mt-6 leading-7 text-[#4a271d]/70">Use this area for a verified capital plan, use of funds, governance, milestones and investor terms. The figures below are placeholders and should not be treated as actual offers.</p><div className="mt-8 overflow-hidden rounded-[18px] border border-[#dfd4bd]"><div className="grid grid-cols-2 bg-[#f7f3eb] p-4 text-[10px] font-black uppercase tracking-[.14em] text-[#8e6d31]"><span>Term</span><span>Illustrative placeholder</span></div>{[["Capital sought","₱ X0,000,000"],["Use of funds","Factory / equipment / working capital"],["Instrument","To be determined"],["Target milestone","XX months"],["Reporting","Quarterly dashboard"]].map(([a,b])=><div key={a} className="grid grid-cols-2 border-t border-[#dfd4bd] p-4 text-sm"><span className="font-bold">{a}</span><span className="text-[#4a271d]/65">{b}</span></div>)}</div></div><div><div className="eyebrow">08 / Competitive frame</div><h2 className="display mt-3 text-5xl leading-[1.02]">Origin is the differentiator.</h2><div className="mt-8 grid gap-3">{[["Farm connection","Direct story from land to product"],["Philippine identity","Capiz cacao + local cultural context"],["Value addition","Chocolate and tablea retain more value locally"],["Diversification","Farm-to-table model beyond a single crop"]].map(([a,b])=><div key={a} className="flex gap-4 rounded-[14px] bg-[#f7f3eb] p-5"><div className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[#c5a059]"/><div><strong className="text-sm">{a}</strong><p className="mt-1 text-sm leading-6 text-[#4a271d]/65">{b}</p></div></div>)}</div></div></div></div></section>

  <section id="faq" className="section bg-[#f7f3eb]"><div className="container max-w-[900px]"><div className="eyebrow">09 / FAQ</div><h2 className="display mt-3 text-5xl md:text-6xl">Questions worth asking.</h2><div className="mt-10">{faqs.map(([q,a],i)=><div key={q} className="border-t border-[#dfd4bd] py-5 last:border-b"><button className="focus flex w-full items-center justify-between text-left" onClick={()=>setFaq(faq===i?null:i)}><span className="display pr-8 text-xl">{q}</span><ChevronDown size={20} className={'shrink-0 transition-transform '+(faq===i?'rotate-180':'')}/></button>{faq===i&&<p className="max-w-2xl pt-4 text-sm leading-7 text-[#4a271d]/65">{a}</p>}</div>)}</div></div></section>

  <section id="contact" className="section bg-[#241611] text-[#fdfbf7]"><div className="container grid gap-12 lg:grid-cols-[1fr_.9fr]"><div><div className="eyebrow text-[#c5a059]">10 / Contact & investor relations</div><h2 className="display mt-3 text-5xl leading-[1.02] md:text-6xl">Let’s build value from origin.</h2><p className="mt-6 max-w-xl leading-7 text-[#f7f3eb]/65">For investment, distribution, wholesale, hospitality, farm partnerships or product inquiries, start the conversation with DADs Farm.</p><div className="mt-8 flex flex-wrap gap-3"><a className="btn btn-gold" href="mailto:dadscacaofarm@gmail.com">Email the team <ArrowRight size={16}/></a><a className="btn btn-outline" href="#top">Back to top</a></div></div><form className="glass rounded-[20px] p-7" onSubmit={e=>e.preventDefault()}><label className="block text-xs font-bold uppercase tracking-[.12em] text-[#c5a059]">Name<input required className="mt-2 w-full rounded-[9px] border border-[#fdfbf7]/15 bg-[#fdfbf7]/5 px-4 py-3 text-sm outline-none"/></label><label className="mt-5 block text-xs font-bold uppercase tracking-[.12em] text-[#c5a059]">Email<input required type="email" className="mt-2 w-full rounded-[9px] border border-[#fdfbf7]/15 bg-[#fdfbf7]/5 px-4 py-3 text-sm outline-none"/></label><label className="mt-5 block text-xs font-bold uppercase tracking-[.12em] text-[#c5a059]">Message<textarea rows={5} className="mt-2 w-full rounded-[9px] border border-[#fdfbf7]/15 bg-[#fdfbf7]/5 px-4 py-3 text-sm outline-none"/></label><button className="btn btn-gold mt-5 w-full">Send inquiry <ArrowRight size={16}/></button><p className="mt-4 text-[11px] leading-5 text-[#f7f3eb]/45">This demo form is presentation-ready. Connect it to your preferred email or CRM endpoint before production launch.</p></form></div></section>
 </main>
 <footer className="border-t border-[#4a271d] bg-[#241611] px-5 py-7 text-[#f7f3eb]/55"><div className="container flex flex-col justify-between gap-4 text-xs md:flex-row"><span className="flex items-center gap-3"><img src="/oguia-logo.webp" alt="" className="h-8 w-8 object-contain" />© {new Date().getFullYear()} O Guia Chocolates by DADs Farm</span><span>Old Guia · Ma-ayon · Capiz · Philippines</span><span>Investor figures marked as placeholders are illustrative only.</span></div></footer>
 </>
}
